
name: Modified Java Version Builds
jobs:
  java:
    name: java (${{ matrix.java }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java:
        - 11
        - 17
    steps:
    - name: Setup Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |-
        python -m pip install --upgrade pip
        pip install inotify
    - name: Run inotifywait
      run: |-
        python3 -c "
        import inotify.adapters
        import inotify.constants
        import os
        from datetime import datetime, timezone
        with open('/home/runner/inotifywait-log-java (${{ matrix.java }}).csv', 'w') as log_file:
          i = inotify.adapters.InotifyTree('/home/runner/work/jitsi/jitsi', inotify.constants.IN_CREATE | inotify.constants.IN_ACCESS)
          for event in i.event_gen(yield_nones=False):
            (_, type_names, path, filename) = event
            now = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%S.%f') + 'Z'
            events = ','.join(type_names)
            log_file.write(f'{now};{path};{filename};{events}\n')
            log_file.flush()
            os.fsync(log_file.fileno())
        " &
    - name: Checkout
      uses: actions/checkout@v3
    - run: touch optcd-3.txt
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: temurin
        check-latest: true
        cache: maven
    - run: touch optcd-4.txt
    - name: Build Java source with Maven
      run: |-
        mvn -B verify -DperformRelease=true -DskipTests
    - run: touch optcd-5.txt
    - name: Upload inotifywait logs
      uses: actions/upload-artifact@v4
      with:
        name: inotifywait-java (${{ matrix.java }})
        path: /home/runner/inotifywait-log-java (${{ matrix.java }}).csv
'on':
- push
- workflow_dispatch
